### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by raulsenaferreira** [tchiluanda/siconfi_atendimento_hospitalar#19]
Hello, I'm a researcher interested in exploring the data and contributing to the repo with more analysis.
Could you please point me to or share the dataset used for the analysis in this work?

Kind regards.

**Comment by fernandobarbalho** [comment]
The data are all public and come from these sources:
[Datasus:](https://github.com/rfsaldanha/microdatasus) data about health facilities address and hospital attendance
[IBGE](https://www.ibge.gov.br/#): data about REGIC model
[Secretaria do Tesouro Nacional](https://siconfi.tesouro.gov.br/siconfi/index.jsf;jsessionid=U5bso6l-RBmLg5-OdG7y9b4A.node2): data about health expenses.
